### ISSUE TITLE
RuntimeError: expected scalar type long int but found float

### ISSUE THREAD

**Issue by syntherick** [CASIA-IVA-Lab/FastSAM#57] opened 2023-06-30 00:13 UTC
I get following error when I run the model

```python
File /root/FastSAM/fastsam/utils.py:17, in adjust_bboxes_to_image_border(boxes, image_shape, threshold)
     14 h, w = image_shape
     16 # Adjust boxes
---> 17 boxes[:, 0] = torch.where(boxes[:, 0] < threshold, 0, boxes[:, 0])  # x1
     18 boxes[:, 1] = torch.where(boxes[:, 1] < threshold, 0, boxes[:, 1])  # y1
     19 boxes[:, 2] = torch.where(boxes[:, 2] > w - threshold, w, boxes[:, 2])  # x2

RuntimeError: expected scalar type long int but found float

```

**Comment by berry-ding** [comment] 2023-06-30 02:48
Hi @syntherick , this appears to be a bug in the code, and we will resolve it as soon as possible. Could you please provide the inference code or command you used? This information would be very helpful for us to investigate the issue.

**Comment by syntherick** [comment] 2023-06-30 02:54
Hi @berry-ding, I get the error for either of following:

```python
!python ./Inference.py  --model_path ../FastSAM-x.pt --img_path ./image.jpg --imgsz 1024
``` 
and

```python
from fastsam import FastSAM, FastSAMPrompt
model = FastSAM('../FastSAM-x.pt')
IMAGE_PATH = './image.jpg'
DEVICE = '0'
everything_results = model(IMAGE_PATH, device=DEVICE, retina_masks=True, imgsz=1024, conf=0.4, iou=0.9,)
```

**Comment by berry-ding** [comment] 2023-06-30 03:28
Hello @syntherick , we have retested and were unable to reproduce the issue. Could you please git pull the latest version of the code and try again? If the problem persists, it might be a bug triggered by specific images. Could you please share the image that caused the problem with us?

**Comment by jq-learning** [comment] 2023-06-30 09:37
I don't why, but I changed the code in utils.py 17-20,  then it works well.    

# Adjust boxes
    boxes[:, 0] = torch.where(boxes[:, 0] < threshold, torch.tensor(0,dtype=torch.float), boxes[:, 0])  # x1
    boxes[:, 1] = torch.where(boxes[:, 1] < threshold, torch.tensor(0,dtype=torch.float), boxes[:, 1])  # y1
    boxes[:, 2] = torch.where(boxes[:, 2] > w - threshold, torch.tensor(w,dtype=torch.float), boxes[:, 2])  # x2
    boxes[:, 3] = torch.where(boxes[:, 3] > h - threshold, torch.tensor(h,dtype=torch.float), boxes[:, 3])  # y2

**Comment by syntherick** [comment] 2023-06-30 14:38
@berry-ding Here is the image which I used
![image](https://github.com/CASIA-IVA-Lab/FastSAM/assets/59579709/ba51c7be-73a8-4906-9e98-1abfabc65aa3)

**Comment by ggsDing** [comment] 2023-07-01 09:04
Hi, I have the exactly same error.

**Comment by ggsDing** [comment] 2023-07-01 09:10
> I don't why, but I changed the code in utils.py 17-20, then it works well.
> 
> # Adjust boxes
> ```
> boxes[:, 0] = torch.where(boxes[:, 0] < threshold, torch.tensor(0,dtype=torch.float), boxes[:, 0])  # x1
> boxes[:, 1] = torch.where(boxes[:, 1] < threshold, torch.tensor(0,dtype=torch.float), boxes[:, 1])  # y1
> boxes[:, 2] = torch.where(boxes[:, 2] > w - threshold, torch.tensor(w,dtype=torch.float), boxes[:, 2])  # x2
> boxes[:, 3] = torch.where(boxes[:, 3] > h - threshold, torch.tensor(h,dtype=torch.float), boxes[:, 3])  # y2
> ```

There will be bugs again again running on cuda devices

**Comment by OroChippw** [comment] 2023-07-03 03:34
> torch.tensor(0,dtype=torch.float)

I meet the same proble , when use the inference demo you provide

from fastsam import FastSAM, FastSAMPrompt

model = FastSAM('./weights/FastSAM.pt')
IMAGE_PATH = './images/dogs.jpg'
DEVICE = 'cpu'
everything_results = model(IMAGE_PATH, device=DEVICE, retina_masks=True, imgsz=1024, conf=0.4, iou=0.9,)
prompt_process = FastSAMPrompt(IMAGE_PATH, everything_results, device=DEVICE)

# everything prompt
ann = prompt_process.everything_prompt()

# bbox default shape [0,0,0,0] -> [x1,y1,x2,y2]
ann = prompt_process.box_prompt(bbox=[200, 200, 300, 300])

# text prompt
ann = prompt_process.text_prompt(text='a photo of a dog')

# point prompt
# points default [[0,0]] [[x1,y1],[x2,y2]]
# point_label default [0] [1,0] 0:background, 1:foreground
ann = prompt_process.point_prompt(points=[[620, 360]], pointlabel=[1])

prompt_process.plot(annotations=ann,output='./output/',)

And it show runtimeerror like this 
  File "inference_demo.py", line 6, in <module>
    everything_results = model(IMAGE_PATH, device=DEVICE, retina_masks=True, imgsz=1024, conf=0.4, iou=0.9,)
  File "E:\OroChiLab\FastSAM\fastsam\model.py", line 99, in __call__
    return self.predict(source, stream, **kwargs)
  File "C:\ProgramData\miniconda3\envs\torch-py37\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\OroChiLab\FastSAM\fastsam\model.py", line 51, in predict
    return self.predictor(source, stream=stream)
  File "C:\ProgramData\miniconda3\envs\torch-py37\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 184, in __call__
    return list(self.stream_inference(source, model))  # merge list of Result into one
  File "C:\ProgramData\miniconda3\envs\torch-py37\lib\site-packages\torch\autograd\grad_mode.py", line 43, in generator_context
    response = gen.send(None)
  File "C:\ProgramData\miniconda3\envs\torch-py37\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 244, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "E:\OroChiLab\FastSAM\fastsam\predict.py", line 27, in postprocess
    critical_iou_index = bbox_iou(full_box[0][:4], p[0][:, :4], iou_thres=0.9, image_shape=img.shape[2:])
  File "E:\OroChiLab\FastSAM\fastsam\utils.py", line 50, in bbox_iou
    boxes = adjust_bboxes_to_image_border(boxes, image_shape)
  File "E:\OroChiLab\FastSAM\fastsam\utils.py", line 19, in adjust_bboxes_to_image_border
    boxes[:, 0] = torch.where(boxes[:, 0] < threshold, 0, boxes[:, 0])  # x1
RuntimeError: expected scalar type __int64 but found float

**Comment by d710055071** [comment] 2023-07-03 03:47
boxes[:, 0] = torch.where(boxes[:, 0] < threshold, torch.tensor(0,dtype=torch.float,device=boxes.device), boxes[:, 0])  # x1
    boxes[:, 1] = torch.where(boxes[:, 1] < threshold, torch.tensor(0,dtype=torch.float,device=boxes.device), boxes[:, 1])  # y1
    boxes[:, 2] = torch.where(boxes[:, 2] > w - threshold, torch.tensor(w,dtype=torch.float,device=boxes.device), boxes[:, 2])  # x2
    boxes[:, 3] = torch.where(boxes[:, 3] > h - threshold, torch.tensor(h,dtype=torch.float,device=boxes.device), boxes[:, 3])  # y2
    
is ok

**Comment by OroChippw** [comment] 2023-07-03 03:50
> ```
> boxes[:, 0] = torch.where(boxes[:, 0] < threshold, torch.tensor(0,dtype=torch.float,device=boxes.device), boxes[:, 0])  # x1
> boxes[:, 1] = torch.where(boxes[:, 1] < threshold, torch.tensor(0,dtype=torch.float,device=boxes.device), boxes[:, 1])  # y1
> boxes[:, 2] = torch.where(boxes[:, 2] > w - threshold, torch.tensor(w,dtype=torch.float,device=boxes.device), boxes[:, 2])  # x2
> boxes[:, 3] = torch.where(boxes[:, 3] > h - threshold, torch.tensor(h,dtype=torch.float,device=boxes.device), boxes[:, 3])  # y2
> ```
> 
> is ok

It worked thanks for your answer😋

**Comment by AAAAAAAyq** [comment] 2023-07-06 01:40
We would close this issue for now to keep the issue tracker organized. However, if the problem persists or if you have any further questions, please feel free to comment here or open a new issue. We value your input and are happy to assist further.

**Closed by AAAAAAAyq** 2023-07-06 01:40 UTC

**Comment by berry-ding** [comment] 2023-07-06 08:35
> 我不知道为什么，但我更改了 utils.py 17-20 中的代码，然后它就可以正常工作了。
> 
> # 调整盒
> ```
> boxes[:, 0] = torch.where(boxes[:, 0] < threshold, torch.tensor(0,dtype=torch.float), boxes[:, 0])  # x1
> boxes[:, 1] = torch.where(boxes[:, 1] < threshold, torch.tensor(0,dtype=torch.float), boxes[:, 1])  # y1
> boxes[:, 2] = torch.where(boxes[:, 2] > w - threshold, torch.tensor(w,dtype=torch.float), boxes[:, 2])  # x2
> boxes[:, 3] = torch.where(boxes[:, 3] > h - threshold, torch.tensor(h,dtype=torch.float), boxes[:, 3])  # y2
> ```

Thank you! we have fixed our codes.
